### ISSUE TITLE
Fedora 34: src/jp2a: error while loading shared libraries: libjpeg.so.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nasseef20** [Talinx/jp2a#8]
Fedora 34 does not have the jp2a package in their repo. So I built the package using instructions from the README.md
All the dependencies were met in my system. 

 ```
autoreconf -vi
./configure --with-jpeg-prefix=/usr/local \
            --with-curl-config=`which curl-config`
make -j
```
went fine with no errors.

However, after a `make -j install`, whenever I try to use jp2a, the error `jp2a: error while loading shared libraries: libjpeg.so.9: cannot open shared object file: No such file or directory` shows up.

So I uninstalled jp2a using `make -j uninstall`, then used

```
autoreconf -vi
./configure --with-jpeg-include=PATH --with-jpeg-lib=PATH\
            --with-curl-config=`which curl-config`
make -j

```
and tried a `make check`. No errors came up.

To test whether it works, ran `src/jp2a` with an image, the same error shows up.

**Comment by Talinx** [comment]
Which libjpeg do you want to use? One from the Fedora packages or one that you installed manually?
In case you installed libjpeg manually, what is the output of `ls /usr/local/lib`? There should be a file called `libjpeg.so.9`. You may need to run `sudo ldconfig /usr/local/lib` so that it can be found.
In case that it still doesn't work I'd be interested in the output of `sudo ldconfig /usr/local/lib -v 2> /dev/null | grep libjpeg`.

**Comment by nasseef20** [comment]
`sudo ldconfig /usr/local/lib` fixed this problem for me. Thanks a lot for taking the time to help me through this problem
